### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-samsung-remote

### ISSUE THREAD

**Issue by mfl76** [nitaybz/homebridge-samsung-remote#2]
I get following error when starting homebridge from my Raspi:

ERROR LOADING PLUGIN homebridge-samsung-remote:
[3/2/2018, 10:34:34 PM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-samsung-remote/node_modules/samsung-tv-remote/index.js:11:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Version 0.4.38

**Comment by mfl76** [comment]
Solved the problem. The nodes.js version was to old...
